### ISSUE TITLE
SSL certificate broken

### ISSUE THREAD

**Issue by yahsieh** [24pullrequests/dashboard#200]
Error message in Google Chrome: "This site is missing a valid, trusted certificate (net::ERR_CERT_COMMON_NAME_INVALID). "
Seems `dashboard.24pullrequests.com` not using Cloudflare certificate as other `*.24pullrequests.com` websites?

**Comment by andrew** [comment]
Tweaked the cloudflare config, i think it's working now, can you confirm? https://dashboard.24pullrequests.com

**Comment by yahsieh** [comment]
It works perfect now!
